baseurl = "/"
Paginate = 5

[params]
  env = "production"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

# datocms:start
title = "Creative Inc."
languageCode = "en"
# datocms:end